<?php

/**
 * @file
 * Contains cupcakes_shop.module.
 */

/**
 * Implements hook_theme() for block templates.
 */
function cupcakes_shop_theme($existing, $type, $theme, $path) {
  return [
    'sale_cupcakes'  => [
      'variables' =>  [
        'data' => []
      ],
      'template' => 'block--sale-cupcakes'
    ],
  ];
}

function cupcakes_shop_node_view($node, $view_mode, $langcode) {
  $twig = \Drupal::service('twig');
  $twig->addGlobal('nid', $node['#node']->get('nid')->getValue());
}

